# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://qpl2026.github.io/'
baseurl: ''
title: 'QPL'
description: 'Official Website for the QPL 2026 Conference'
permalink: pretty
# logo: "/images/QPL-logo-final-no-title.svg"

# Pagination
# paginate: 5
# paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Local Information
  url: /local_info/
- title: Contact
  url: /#contact
- title: Code of Conduct
  url: /#code-of-conduct
# - title: Sponsors
#   url: /#platinum-sponsors
# - title: Accepted Submissions
#   url: /accepted/
# - title: Registration
#   url: /registration/
# - title: Program
#   url: /program/

# Footer nav
navigation_footer:
  - title: Back to top
    url: "#top"

# Collections
# collections:
#  posts:
#  title: Posts
#  output: true
#  description: "My thoughts and ideas"
#  feature_text: |
#    Welcome to my blog
#  feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
